// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/44smkn/ri_normalized_unit_exporter/pkg/aws/services (interfaces: RDS)

// Package services is a generated GoMock package.
package services

import (
	context "context"
	reflect "reflect"

	rds "github.com/aws/aws-sdk-go-v2/service/rds"
	types "github.com/aws/aws-sdk-go-v2/service/rds/types"
	gomock "github.com/golang/mock/gomock"
)

// MockRDS is a mock of RDS interface.
type MockRDS struct {
	ctrl     *gomock.Controller
	recorder *MockRDSMockRecorder
}

// MockRDSMockRecorder is the mock recorder for MockRDS.
type MockRDSMockRecorder struct {
	mock *MockRDS
}

// NewMockRDS creates a new mock instance.
func NewMockRDS(ctrl *gomock.Controller) *MockRDS {
	mock := &MockRDS{ctrl: ctrl}
	mock.recorder = &MockRDSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRDS) EXPECT() *MockRDSMockRecorder {
	return m.recorder
}

// DescribeDBInstancesAsList mocks base method.
func (m *MockRDS) DescribeDBInstancesAsList(arg0 context.Context, arg1 *rds.DescribeDBInstancesInput) ([]types.DBInstance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeDBInstancesAsList", arg0, arg1)
	ret0, _ := ret[0].([]types.DBInstance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeDBInstancesAsList indicates an expected call of DescribeDBInstancesAsList.
func (mr *MockRDSMockRecorder) DescribeDBInstancesAsList(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeDBInstancesAsList", reflect.TypeOf((*MockRDS)(nil).DescribeDBInstancesAsList), arg0, arg1)
}

// DescribeReservedDBInstancesAsList mocks base method.
func (m *MockRDS) DescribeReservedDBInstancesAsList(arg0 context.Context, arg1 *rds.DescribeReservedDBInstancesInput) ([]types.ReservedDBInstance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeReservedDBInstancesAsList", arg0, arg1)
	ret0, _ := ret[0].([]types.ReservedDBInstance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeReservedDBInstancesAsList indicates an expected call of DescribeReservedDBInstancesAsList.
func (mr *MockRDSMockRecorder) DescribeReservedDBInstancesAsList(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeReservedDBInstancesAsList", reflect.TypeOf((*MockRDS)(nil).DescribeReservedDBInstancesAsList), arg0, arg1)
}
